version: '3.7'

services:
  database:
    platform: linux/x86_64
    image: 'mysql:latest'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: snowtricks
      MYSQL_DATABASE: snowtricks
      MYSQL_USER: snowtricks
      MYSQL_PASSWORD: snowtricks
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - database
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
  mailer:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 1080 --smtp 1025 --hide-extensions STARTTLS
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: always
  app:
    image: snowtricks:latest
    ports:
      - "8010:80"
    environment:
      DATABASE_URL: mysql://snowtricks:snowtricks@database:3306/snowtricks
      MAILER_DSN: smtp://mailer:1025